// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Adminclasificaunbug() {
    // Test name: admin clasifica un bug
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.Navigate().GoToUrl("http://localhost:4200/login");
    // 2 | setWindowSize | 1920x1040 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    // 3 | click | css=.mat-flat-button > .mat-button-wrapper | 
    driver.FindElement(By.CssSelector(".mat-flat-button > .mat-button-wrapper")).Click();
    // 4 | click | css=.cdk-focused | 
    driver.FindElement(By.CssSelector(".cdk-focused")).Click();
    // 5 | click | id=mat-input-2 | 
    driver.FindElement(By.Id("mat-input-2")).Click();
    // 6 | type | id=mat-input-2 | fake name
    driver.FindElement(By.Id("mat-input-2")).SendKeys("fake name");
    // 7 | type | id=mat-input-3 | fake description
    driver.FindElement(By.Id("mat-input-3")).SendKeys("fake description");
    // 8 | type | id=mat-input-4 | fake comment
    driver.FindElement(By.Id("mat-input-4")).SendKeys("fake comment");
    // 9 | click | css=.ng-tns-c83-6 > .mat-form-field-infix | 
    driver.FindElement(By.CssSelector(".ng-tns-c83-6 > .mat-form-field-infix")).Click();
    // 10 | click | css=#mat-option-2 > .mat-option-text | 
    driver.FindElement(By.CssSelector("#mat-option-2 > .mat-option-text")).Click();
    // 11 | click | css=#save > .mat-button-wrapper | 
    driver.FindElement(By.CssSelector("#save > .mat-button-wrapper")).Click();
  }
}
